# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Site

on:
  push:
    paths:
      - .github/workflows/build-and-deploy.yml
      - "docs/**"
      - "src/**"
      - "static/**"
      - "**.js"
      - "**.json"
      - "**.lock"
  pull_request:
    paths:
      - .github/workflows/build-and-deploy.yml
      - "docs/**"
      - "src/**"
      - "static/**"
      - "**.js"
      - "**.json"
      - "**.lock"

jobs:
  build:
    name: Deploy Site
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish
        uses: cloudflare/pages-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: recyclarr-wiki
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
