# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Site

on:
  push:
    paths-ignore:
      - .markdownlint.json
      - "*.md"
      - "*.ps1"
      - ".git*"
  pull_request:
    paths-ignore:
      - .markdownlint.json
      - "*.md"
      - "*.ps1"
      - ".git*"

jobs:
  build:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: yarn install && yarn run build

      - name: Publish
        uses: cloudflare/pages-action@1
        if: github.ref == 'refs/heads/master'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: recyclarr-wiki
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
